### ISSUE TITLE
Plot user and movie rating distributions

### ISSUE THREAD

**Issue by lacic** [lfadljevic/MovieLens#1]
Create a distribution plots (pandas, seaborn) which shows how users rate and movies are getting rated (two plots).

Each script should be a seperate ipython file. Plots should be stored in a manually created "plots" folder.

**Comment by lacic** [comment]
Any progress? @lfadljevic

**Comment by lfadljevic** [comment]
I managed to produce the plot that shows how users rate but forgot to write you.
I didn't accomplish the second plot because my exams started and I had to change my focus. @lacic

**Comment by lacic** [comment]
No excuses needed, was only interested in the progress. Didn't see the plot thou. :)

**Comment by lfadljevic** [comment]
Results are uploaded. Moving to next task. @lacic

**Comment by lacic** [comment]
Can be closed, as the point of the issue was to get familiar with the dataset and basic plotting functions in python. :)
